import type { LanguageStrings, Quote } from './types';
import { v4 as uuidv4 } from 'uuid';

export const STRINGS: LanguageStrings = {
  es: {
    title: 'Generador de Cotizaciones de Proyectos',
    quoteFor: 'Cotización para',
    projectName: 'Nombre del Proyecto',
    clientName: 'Nombre del Cliente',
    address: 'Dirección',
    submissionDeadline: 'Fecha Límite de Entrega',
    projectDescription: 'Descripción del Proyecto',
    generateWithAI: 'Generar con IA',
    generating: 'Generando...',
    items: 'Partidas',
    description: 'Descripción',
    quantity: 'Cantidad',
    unit: 'Unidad',
    material: 'Material',
    unitPrice: 'Precio Unitario',
    labor: 'Mano de Obra (Unit.)',
    total: 'Total',
    addItem: 'Agregar Partida',
    subtotal: 'Subtotal',
    tax: 'Impuesto',
    grandTotal: 'Total General',
    printQuote: 'Imprimir Cotización',
    remove: 'Eliminar',
    currency: 'Moneda',
    geminiModalTitle: 'Generador de Descripción de Proyecto',
    geminiModalPrompt: 'Escriba los puntos clave de su propuesta. La IA los convertirá en una descripción profesional.',
    geminiModalButton: 'Generar Descripción',
    geminiModalResult: 'Descripción Generada:',
    insertDescription: 'Insertar Descripción',
    close: 'Cerrar',
    resetQuote: 'Restablecer',
    resetConfirmation: '¿Estás seguro de que quieres restablecer la cotización a los valores predeterminados? Se perderán todos los cambios actuales.',
  },
  en: {
    title: 'Project Quotation Generator',
    quoteFor: 'Quotation For',
    projectName: 'Project Name',
    clientName: 'Client Name',
    address: 'Address',
    submissionDeadline: 'Submission Deadline',
    projectDescription: 'Project Description',
    generateWithAI: 'Generate with AI',
    generating: 'Generating...',
    items: 'Line Items',
    description: 'Description',
    quantity: 'Quantity',
    unit: 'Unit',
    material: 'Material',
    unitPrice: 'Unit Price',
    labor: 'Labor (Unit)',
    total: 'Total',
    addItem: 'Add Item',
    subtotal: 'Subtotal',
    tax: 'Tax',
    grandTotal: 'Grand Total',
    printQuote: 'Print Quote',
    remove: 'Remove',
    currency: 'Currency',
    geminiModalTitle: 'Project Description Generator',
    geminiModalPrompt: 'Enter the key points of your proposal. The AI will turn them into a professional description.',
    geminiModalButton: 'Generate Description',
    geminiModalResult: 'Generated Description:',
    insertDescription: 'Insert Description',
    close: 'Close',
    resetQuote: 'Reset',
    resetConfirmation: 'Are you sure you want to reset the quote to its default values? All current changes will be lost.',
  },
};

export const INITIAL_QUOTE: Quote = {
  projectName: 'Proyecto de Renovación de Pisos',
  clientName: 'Parroquia Nuestra Señora de Guadalupe',
  address: '694 Weston Rd, Toronto, Ontario',
  submissionDeadline: '2025-10-15',
  projectDescription: 'Suministro e instalación de nuevos pisos de vinilo y/o cerámica en varias áreas de la iglesia, de acuerdo con las especificaciones del CFP.',
  lineItems: [
    { id: uuidv4(), description: 'Templo Princi', quantity: 2000, unit: 'pies²', material: 'LVP Cc', unitPrice: 5.5, laborUnitPrice: 2.5 },
    { id: uuidv4(), description: 'Escalones a b', quantity: 16, unit: 'escalones', material: 'LVPMa', unitPrice: 0, laborUnitPrice: 300 },
    { id: uuidv4(), description: 'Descanso a b', quantity: 1, unit: 'unidad', material: 'Mader', unitPrice: 0, laborUnitPrice: 400 },
    { id: uuidv4(), description: 'Escalones a c', quantity: 16, unit: 'escalones', material: 'Mader', unitPrice: 0, laborUnitPrice: 300 },
    { id: uuidv4(), description: 'Descanso a c', quantity: 2, unit: 'unidad', material: 'Mader', unitPrice: 0, laborUnitPrice: 400 },
    { id: uuidv4(), description: 'Área del Corc', quantity: 550, unit: 'pies²', material: 'LVP Cc', unitPrice: 5.5, laborUnitPrice: 2.5 },
    { id: uuidv4(), description: 'Remoción y r', quantity: 1, unit: 'lote', material: 'N/A', unitPrice: 0, laborUnitPrice: 3200 },
    { id: uuidv4(), description: 'Bancas quitar', quantity: 1, unit: 'Lote', material: 'Materi', unitPrice: 0, laborUnitPrice: 1000 },
    { id: uuidv4(), description: 'Area Altar', quantity: 550, unit: 'pies²', material: 'tile', unitPrice: 8, laborUnitPrice: 3 },
  ],
  taxRate: 13,
  currency: 'CAD',
};