import type { LanguageStrings, Quote } from './types';
import { v4 as uuidv4 } from 'uuid';

export const STRINGS: LanguageStrings = {
  es: {
    title: 'Generador de Cotizaciones de Proyectos',
    quoteFor: 'Cotización para',
    projectName: 'Nombre del Proyecto',
    clientName: 'Nombre del Cliente',
    address: 'Dirección',
    submissionDeadline: 'Fecha Límite de Entrega',
    projectDescription: 'Descripción del Proyecto',
    generateWithAI: 'Generar con IA',
    generating: 'Generando...',
    items: 'Partidas',
    description: 'Descripción',
    quantity: 'Cantidad',
    unit: 'Unidad',
    material: 'Material',
    unitPrice: 'Precio Unitario',
    labor: 'Mano de Obra (Unit.)',
    total: 'Total',
    addItem: 'Agregar Partida',
    subtotal: 'Subtotal',
    tax: 'Impuesto',
    grandTotal: 'Total General',
    printQuote: 'Imprimir Cotización',
    remove: 'Eliminar',
    currency: 'Moneda',
    geminiModalTitle: 'Generador de Descripción de Proyecto',
    geminiModalPrompt: 'Escriba los puntos clave de su propuesta. La IA los convertirá en una descripción profesional.',
    geminiModalButton: 'Generar Descripción',
    geminiModalResult: 'Descripción Generada:',
    insertDescription: 'Insertar Descripción',
    close: 'Cerrar',
  },
  en: {
    title: 'Project Quotation Generator',
    quoteFor: 'Quotation For',
    projectName: 'Project Name',
    clientName: 'Client Name',
    address: 'Address',
    submissionDeadline: 'Submission Deadline',
    projectDescription: 'Project Description',
    generateWithAI: 'Generate with AI',
    generating: 'Generating...',
    items: 'Line Items',
    description: 'Description',
    quantity: 'Quantity',
    unit: 'Unit',
    material: 'Material',
    unitPrice: 'Unit Price',
    labor: 'Labor (Unit)',
    total: 'Total',
    addItem: 'Add Item',
    subtotal: 'Subtotal',
    tax: 'Tax',
    grandTotal: 'Grand Total',
    printQuote: 'Print Quote',
    remove: 'Remove',
    currency: 'Currency',
    geminiModalTitle: 'Project Description Generator',
    geminiModalPrompt: 'Enter the key points of your proposal. The AI will turn them into a professional description.',
    geminiModalButton: 'Generate Description',
    geminiModalResult: 'Generated Description:',
    insertDescription: 'Insert Description',
    close: 'Close',
  },
};

export const INITIAL_QUOTE: Quote = {
  projectName: 'Proyecto de Renovación de Pisos',
  clientName: 'Parroquia Nuestra Señora de Guadalupe',
  address: '694 Weston Rd, Toronto, Ontario',
  submissionDeadline: '2025-10-15',
  projectDescription: 'Suministro e instalación de nuevos pisos de vinilo y/o cerámica en varias áreas de la iglesia, de acuerdo con las especificaciones del CFP.',
  lineItems: [
    { id: uuidv4(), description: 'Templo Principal y Altar', quantity: 2150, unit: 'pies²', material: 'LVP Comercial', unitPrice: 5.5, laborUnitPrice: 2.35 },
    { id: uuidv4(), description: 'Escalones a baños/salón', quantity: 15, unit: 'escalones', material: 'LVP Anti-deslizante', unitPrice: 90, laborUnitPrice: 53 },
    { id: uuidv4(), description: 'Descanso a baños/salón', quantity: 1, unit: 'unidad', material: 'LVP Anti-deslizante', unitPrice: 400, laborUnitPrice: 200 },
    { id: uuidv4(), description: 'Escalones a coro', quantity: 12, unit: 'escalones', material: 'LVP Anti-deslizante', unitPrice: 90, laborUnitPrice: 50 },
    { id: uuidv4(), description: 'Descanso a coro', quantity: 1, unit: 'unidad', material: 'LVP Anti-deslizante', unitPrice: 350, laborUnitPrice: 150 },
    { id: uuidv4(), description: 'Área del Coro y detrás del coro', quantity: 540, unit: 'pies²', material: 'LVP Comercial', unitPrice: 5.5, laborUnitPrice: 3.70 },
    { id: uuidv4(), description: 'Remoción y reinstalación de bancas', quantity: 1, unit: 'lote', material: 'N/A', unitPrice: 0, laborUnitPrice: 2500 },
    { id: uuidv4(), description: 'Eliminación de escombros y limpieza', quantity: 1, unit: 'lote', material: 'N/A', unitPrice: 0, laborUnitPrice: 800 },
  ],
  taxRate: 13,
  currency: 'CAD',
};